[project]
name = "write-workflows"
version = "0.1.0"
description = "Write workflows with Prefect course repository"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prefect==3.2.5",
]
